pub const ATTESTATION_VERSION: u8 = 2;

pub const ECONOMIC_STATUS_ACTIVE: u8 = 1;
pub const ECONOMIC_STATUS_REDEEMED: u8 = 2;
pub const ECONOMIC_STATUS_CLOSED: u8 = 3;


pub const REDEMPTION_STATUS_REQUESTED: u8 = 1;
pub const REDEMPTION_STATUS_SETTLED: u8 = 2;
